services:
  users_postgres:
    image: postgres:15
    container_name: users_postgres
    environment:
      POSTGRES_DB: ${USERS_PG_DATABASE:?error}
      POSTGRES_USER: ${USERS_PG_USER:?error}
      POSTGRES_PASSWORD: ${USERS_PG_PASSWORD:?error}
      PGPORT: ${USERS_PG_PORT:-5432}
    ports:
      - "${USERS_PG_PORT}:${USERS_PG_PORT}"
    volumes:
      - users_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${USERS_PG_USER} -d ${USERS_PG_DATABASE} -p ${USERS_PG_PORT}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: on-failure

  users_api:
    build:
      context: ./users_info
    container_name: users_api
    environment:
      API_PORT: ${USERS_API_PORT:-8000}
    ports:
      - "${USERS_API_PORT:-8000}:${USERS_API_PORT:-8000}"
    depends_on:
      users_postgres:
        condition: service_healthy


volumes:
  users_pg_data:
