"""not-null-emails

Revision ID: 02
Revises: 01
Create Date: 2024-03-27 12:10:43.040475

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "02"
down_revision: Union[str, None] = "01"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("emails_table", "address", existing_type=sa.VARCHAR(length=100), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("emails_table", "address", existing_type=sa.VARCHAR(length=100), nullable=True)
    # ### end Alembic commands ###
