"""add-friendships

Revision ID: 03
Revises: 02
Create Date: 2024-03-27 17:06:15.657845

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "03"
down_revision: Union[str, None] = "02"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "friend_relationships_table",
        sa.Column("request_user_id", sa.Uuid(), nullable=False),
        sa.Column("accept_user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["accept_user_id"], ["users_table.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["request_user_id"], ["users_table.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("request_user_id", "accept_user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("friend_relationships_table")
    # ### end Alembic commands ###
